### ISSUE TITLE
Variables names and comments

### ISSUE THREAD

**Issue by FraGoTe** [ivandevp/node-prompt#2]
You should define the language you are going to use because there are variables in spanish and english.

**Comment by ivandevp** [comment]
First, the code was made for teaching spanish beginner coders.
Now, language is defined in commit [991ec9528abbdb985d74663f5785dfa62d9417b7](https://github.com/ivandevp/node-prompt/commit/991ec9528abbdb985d74663f5785dfa62d9417b7)
